#!/usr/bin/env bash

OLD_DIR = $HOME/.config/yadm/repo.git/info
NEW_DIR = $HOME/.local/share/yadm/repo.git/info

[ -d $NEW_DIR ] && EXCLUDE_PATH = $NEW_DIR/exclude || EXCLUDE_PATH = $OLD_DIR/exclude

cat > $EXCLUDE_PATH <<EOL
# ignore everything
/*

# except
!/.config
/.config/*
!/.config/fish
!/.config/fish/**
/.config/fish/fish_variables

!/.config/yadm
!/.config/yadm/**

!/.config/git

!/.gitconfig
!/.ssh/config

EOL
