-- Generated by hyprmoncfg

hl.monitor({
  output = "HDMI-A-1",
  mode = "3840x2160@60.00",
  position = "3820x-513",
  scale = 1.5,
})

hl.monitor({
  output = "desc:Microstep MPG321UR-QD",
  mode = "3840x2160@143.99",
  position = "3820x927",
  scale = 1.33,
  vrr = 1,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Microstep MPG321UR-QD", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Microstep MPG321UR-QD" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Microstep MPG321UR-QD" })
