-- Generated by hyprmoncfg

hl.monitor({
  output = "DP-2",
  mode = "2560x1600@59.97",
  position = "6707x1532",
  scale = 1.6,
})

hl.monitor({
  output = "HDMI-A-1",
  mode = "3840x2160@119.88",
  position = "3820x927",
  scale = 1.5,
  vrr = 1,
  mirror = "desc:Microstep MPG321UR-QD",
})

hl.monitor({
  output = "desc:Microstep MPG321UR-QD",
  mode = "3840x2160@143.99",
  position = "3820x927",
  scale = 1.33,
  vrr = 1,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Microstep MPG321UR-QD", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Microstep MPG321UR-QD" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Microstep MPG321UR-QD" })
hl.workspace_rule({ workspace = "4", monitor = "DP-2", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "DP-2" })
hl.workspace_rule({ workspace = "6", monitor = "DP-2" })
