-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Microstep MPG321UR-QD",
  mode = "3840x2160@143.99",
  position = "0x0",
  scale = 1.33,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Display Corp. ATNA60CL10-0",
  mode = "2880x1800@120.00",
  position = "2887x546",
  scale = 1.67,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Microstep MPG321UR-QD", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Microstep MPG321UR-QD" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Microstep MPG321UR-QD" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Microstep MPG321UR-QD" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Samsung Display Corp. ATNA60CL10-0", default = true, persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "desc:Samsung Display Corp. ATNA60CL10-0" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Samsung Display Corp. ATNA60CL10-0" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Samsung Display Corp. ATNA60CL10-0" })
