-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Samsung Display Corp. ATNA60CL10-0",
  mode = "2880x1800@120.00",
  position = "0x0",
  scale = 1.5,
  vrr = 1,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Samsung Display Corp. ATNA60CL10-0", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Samsung Display Corp. ATNA60CL10-0" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Samsung Display Corp. ATNA60CL10-0" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Samsung Display Corp. ATNA60CL10-0" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Samsung Display Corp. ATNA60CL10-0" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Samsung Display Corp. ATNA60CL10-0" })
