[tools]
claude = "latest"
codex = "latest"
go = "latest"
node = "latest"
opencode = "latest"
ruby = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
