general {
    lock_cmd = OMARCHY_LOCK_ONLY=true omarchy system lock          # lock screen and 1password
    before_sleep_cmd = OMARCHY_LOCK_ONLY=true omarchy system lock  # lock before suspend without scheduling display off.
    after_sleep_cmd = sleep 1 && omarchy system wake               # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                             # wait until screen is locked
}

# Battery: lock at 3min
listener {
    timeout = 180
    on-timeout = omarchy-is-power-on-battery && OMARCHY_LOCK_ONLY=true omarchy system lock
}

# Battery: keyboard backlight off at 3min
listener {
    timeout = 180
    on-timeout = omarchy-is-power-on-battery && omarchy brightness keyboard off
    on-resume = omarchy brightness keyboard restore
}

# Battery: display off at 5min
listener {
    timeout = 300
    on-timeout = omarchy-is-power-on-battery && omarchy brightness display off
    on-resume = omarchy system wake
}

# Battery: suspend at 10min
listener {
    timeout = 600
    on-timeout = omarchy-is-power-on-battery && systemctl suspend
}

# AC: start Omarchy screensaver at 3min
listener {
    timeout = 180
    on-timeout = omarchy-is-power-on-ac && (pidof hyprlock || omarchy launch screensaver)
}

# AC: lock at 5min
listener {
    timeout = 300
    on-timeout = omarchy-is-power-on-ac && OMARCHY_LOCK_ONLY=true omarchy system lock
}

# AC: keyboard backlight off at 3min
listener {
    timeout = 180
    on-timeout = omarchy-is-power-on-ac && omarchy brightness keyboard off
    on-resume = omarchy brightness keyboard restore
}

# AC: display off at 10min
listener {
    timeout = 600
    on-timeout = omarchy-is-power-on-ac && omarchy brightness display off
    on-resume = omarchy system wake
}
